### ISSUE TITLE
Synapse SQL Pool access disabled by default

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#102]
Lab 7 > Exercise 3 > Task 4 > Step 1

In Synapse SQL Pools, "Allow Azure services and resources to access this server" is DISABLED by default under Firewalls and Virtual Networks. 

This setting causes the connection between ADF Sink Transformation and the Synapse SQL pool to fail.

FIX: Add a step to Allow Azure services and resources to access this server in the Synapse SQL pool.

**Comment by VitalyMCT** [comment]
@chris-utter , that's strange. When the server was provisioned back in Lab 5 this setting was turned on. Screenshot below. Are you sure you've completed Lab 5 exactly per instructions?

![image](https://user-images.githubusercontent.com/1765732/88222058-6221c480-cc33-11ea-8544-bcb89b82b1f8.png)

**Comment by chris-utter** [comment]
Hi Vitaly, I am the instructor for this course. I have delivered this course several times in the last few weeks, and each had students who were unable to connect because of this setting.
It might make sense to add a check in Lab 7.

**Comment by madiepev** [comment]
This issue occurs because the check box isn't there anymore when creating a new server:
![image](https://user-images.githubusercontent.com/48012580/95084729-8f541e00-071e-11eb-90e6-9522f82bedb3.png)
It now has to be specified in the "Networking" tab when you create the Azure Synapse Analytics.

**Comment by ctesta-oneillmsft** [comment]
labs have been updated to use Synapse Workspace
