### ISSUE TITLE
DP-200-06: Stream Analytics job output needs to define minimum rows and maximum time

### ISSUE THREAD

**Issue by andreas-wilm** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#103]
Hello there,

in Task 3 "Specify the a Stream Analytics job output of" [DP-200-06](https://github.com/MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution/blob/master/instructions/dp-200-06_instructions.md) the options minimum rows and maximum time cannot be left blank anymore.

Thanks

**Comment by ctesta-oneillmsft** [comment]
resolved and released
