### ISSUE TITLE
issue in lab 3 spark conf setup

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#105]
https://github.com/MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution/blob/master/instructions/dp-200-03_instructions.md

**Hello in task 4** 
I have (I think) correcly entered the info
**Tks for your help**

spark.conf.set("fs.azure.account.auth.type", "OAuth")
spark.conf.set("fs.azure.account.oauth.provider.type", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.conf.set("fs.azure.account.oauth2.client.id.awdlsstudmalta.dfs.core.windows.net", "547e35f2-972c-450e-897e-3021ff97404d")
spark.conf.set("fs.azure.account.oauth2.client.secret.awdlsstudmalta.dfs.core.windows.net", "7~c~mCcF_f0iI2Vh8S1jCh4-~R4pdLwE35")
spark.conf.set("fs.azure.account.oauth2.client.endpoint.awdlsstudmalta.dfs.core.windows.net", "https://login.microsoftonline.com/4333438a-815c-44ab-bb1d-d293a34231ca/oauth2/token")

But when I run val df = spark.read.json("abfss://logs@awdlsstudmalta.dfs.core.windows.net/preferences.json")
I have each time the same error

AADToken: HTTP connection failed for getting token from AzureAD. Http response: 401 Unauthorized
Content-Type: application/json; charset=utf-8 Content-Length: 698 Request ID: c7bea96f-c779-4720-83ed-8a1b2cfa0a00 Proxies: none
First 1K of Body: {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials\r\nTrace ID: c7bea96f-c779-4720-83ed-8a1b2cfa0a00\r\nCorrelation ID: 7cd72620-19d5-45da-8072-7064c2b97958\r\nTimestamp: 2020-07-24 12:42:15Z","error_codes":[7000222],"timestamp":"2020-07-24 12:42:15Z","trace_id":"c7bea96f-c779-4720-83ed-8a1b2cfa0a00","correlation_id":"7cd72620-19d5-45da-8072-7064c2b97958","error_uri":"https://login.microsoftonline.com/error?code=7000222"}

**Comment by ctesta-oneillmsft** [comment]
unable to reproduce this issue
