### ISSUE TITLE
Install Storage Explorer UI changed

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#108]
Lab 2 > Exercise 4 > Task 1: Install Storage Explorer

1. Step One directs the student to a blob storage container: In the Azure portal, in the awdlsstudxx - Containers screen, click on the data item in the list. This instruction should be removed.

Azure Storage Explorer is on the Overview page of the storage account, not on the Container page.

2. If the student is in the Learn On Demand system Azure Storage Explorer is pre-installed.

3. **Azure Storage Explorer is no longer required to upload files in a data lake store.  There is now an Upload button provided.**

**Comment by ctesta-oneillmsft** [comment]
resolved and released
