### ISSUE TITLE
SQL DW renaming to Synapse

### ISSUE THREAD

**Issue by madiepev** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#109]
Exercise 2. Task 1. 
Bullet point 5:
Currently is: "From the SQL Data Warehouse blade, create an Azure Synapse Analytics with the following settings:"
Should be: "Create an Azure Synapse Analytics with the following settings:" (there is no SQL Data Warehouse blade)
Currently is: "In the Database details section, type in the following information"
Should be: "In the SQL pool details section"
Currently is: "Database warehouse name: Warehousexx, where xx are your initials."
Should be: "SQL pool name: ..."
Bullet point 6: 
Currently is: "In the SQL Data Warehouse screen, click Review + create."
Should be: "In the Azure Synapse Analytics screen, ..."
Currently is: "In the SQL Data Warehouse blade, click Create."
Should be: "In the Azure Synapse Analytics blade, ..." 
Screenshots included in these instructions are also outdated.

**Comment by ctesta-oneillmsft** [comment]
resolved and released
