### ISSUE TITLE
Lab 8 - Azure Security Centre Upgrade (Lab is out of Sync)

### ISSUE THREAD

**Issue by meetnavpk** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#110]
Module 8 / Lab 8 - Security the recent updates of Azure Security Centre have removed the Resource Security and Hygiene section (which might have moved elsewhere) Labs are still referring to it, can this please be updated accordingly with-in sync with new changes (I am adding ticket on GitHub), Also does anyone the workaround for now?

**Comment by ctesta-oneillmsft** [comment]
resolved and released
