### ISSUE TITLE
Lab 6 - Performing Real-Time Analytics with Stream Analytics

### ISSUE THREAD

**Issue by GhumanNavneet** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#111]
JSON file not appearing in step3 task 6 exercise 4 -> performed all steps
![image](https://user-images.githubusercontent.com/33318387/95518403-93af5e00-09e0-11eb-9b75-46910547eb04.png)

**Comment by GhumanNavneet** [comment]
Any update on this??

**Comment by Derekp20** [comment]
Are you seeing records produced when you use the "test" option of the Query part of the Stream Analytics job?

**Comment by GhumanNavneet** [comment]
yes i got the records when i run the query

**Comment by GhumanNavneet** [comment]
any update

**Comment by ctesta-oneillmsft** [comment]
resolved and released
