### ISSUE TITLE
Lab 7 - Orchestrating Data Movement with Azure Data Factory

### ISSUE THREAD

**Issue by bonzz** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#113]
In Lab 7 - Orchestrating Data Movement with Azure Data Factory

In Exercise 4: Azure Data Factory and Databricks

In Task 8: Verify the output

I am not able to see the event type of starting which is triggered at the same time when the pipeline started to run. Followed the steps very carefully and also crossed check with the below link 

https://docs.microsoft.com/en-us/azure/data-factory/transform-data-using-databricks-notebook#create-a-pipeline 

Can u help me out with where I went wrong or can u just check if an issue persists?

**Comment by bonzz** [comment]
Hi,

Can someone please check into this issue?

Thanks & Regards
Bony

**Comment by davidcwalls** [comment]
Is it possible your Databricks cluster was already running?  If it was, you wouldn't see a new start entry in the log..

**Comment by ctesta-oneillmsft** [comment]
unable to repro this issue. All contents have been updated
