### ISSUE TITLE
Storage Account Tier selection

### ISSUE THREAD

**Issue by JuanQuijano** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#114]
Storage account tier selection changed to Advanced tab

dp-200-02_instructions.md 
-> Lab 2 - Working with Data Storage 
-> Exercise 2: Create an Azure Storage Account 
-> Task 2: Create and configure a storage account
-> Under the instance details, specify the following settings
-> Access tier (default): Hot.

This is no longer there.
The following lines should be added:

-> Click on the Advanced tab.
-> Under Blob Storage, specify the following setting
-> Access tier (default): Hot.

**Comment by ctesta-oneillmsft** [comment]
resolved and released
