### ISSUE TITLE
Lab 2, Exercise 2, Task 2, Step 5 - Access Tier moved from Basics tab to Advanced tab; add new Data Protection tab

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#117]
Lab 2, Exercise 2, Task 2, Step 5 - Access Tier moved from Basics tab to Advanced tab; add new Data Protection tab
Given that Access Tier defaults to Hot, consider the following updates to reflect portal updates:
1.  Remove bulleted item:  Access tier (default): Hot.
2.  New portal screenshot to show updated Basics tab and new Data Protection tab, see attached.
![dp-200-lab2-exercise2](https://user-images.githubusercontent.com/11367710/99409387-8b372680-28ae-11eb-82f7-d6a40569e75b.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved and released
