### ISSUE TITLE
Lab 3, Exercise 2, Task 1, Step 5 Update screenshot and order of settings to reflect portal update

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#121]
Step 5:  Update screenshot and order of settings to reflect portal update.  Note:  Deploy Azure Databricks workspace in your Virtual Network: No. is now located on the Networking tab.  Given that it is the default setting, I removed it from step 5.  Also, Location:  changed to Region and the title of the blade changed.

5. In the **Create an Azure Databricks workspace** blade, create an Azure Databricks Workspace with the following settings:

Subscription: the name of the subscription you are using in this lab
Resource group: awrgstudxx, where xx are your initials.
Workspace name: awdbwsstudxx, where xx are your initials.
**Region:** the name of the Azure region which is closest to the lab location and where you can provision Azure VMs.
Pricing Tier: Premium (+ Role-based access controls).

![databricksbasicstab](https://user-images.githubusercontent.com/11367710/99452071-5217aa00-28e0-11eb-8bde-ffebee1acf72.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved and released
