### ISSUE TITLE
Lab 3, Exercise 2, Task 2, Step 4 update screenshot

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#122]
Lab 3, Exercise 2, Task 2, Step 4 update screenshot

![databricksbasicstab2](https://user-images.githubusercontent.com/11367710/99454649-f2bb9900-28e3-11eb-99fb-af36f8a59a2b.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved and released
