### ISSUE TITLE
Lab 3, Exercise 2, Task 3, Step 3 Update Databricks Runtime Version to 7.3 LTS and update screenshot

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#123]
Lab 3, Exercise 2, Task 3, Step 3 Update Databricks Runtime Version to 7.3 LTS and update screenshot

3. In the Create Cluster screen, under New Cluster, create a Databricks Cluster with the following settings, and then click on Create Cluster:

Cluster name: awdbclstudxx, where xx are your initials.

Cluster Mode: Standard

Pool: None

Databricks Runtime Version: **Runtime: 7.3 LTS (Scala 2.12, Spark 3.0.1)**

Make sure you select the Terminate after 60 minutes of inactivity check box. If the cluster isn't being used, provide a duration (in minutes) to terminate the cluster.

Leave all the remaining options to their current settings.

![createcluster](https://user-images.githubusercontent.com/11367710/99458309-893e8900-28e9-11eb-8928-d8d8626ace35.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved and released
