### ISSUE TITLE
Lab 4, Exercise 1, Task 1, Step 5 - update screenshot to include new Backup Policy tab

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#124]
Lab 4, Exercise 1, Task 1, Step 5 - update screenshot to include new Backup Policy tab, as attached.
![cosmosbasicstab](https://user-images.githubusercontent.com/11367710/99548049-78d3f000-2975-11eb-851f-a3927ac9d565.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved and released
