### ISSUE TITLE
Lab5, Exercise 2, Task 1, Step 5 - change Database warehouse name to SQL pool name and update screenshot

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#125]
Lab5, Exercise 2, Task 1, Step 5 - change Database warehouse name to SQL pool name and update screenshot

Change bulleted item:  Database warehouse name: Warehousexx, where xx are your initials.
To:  **SQL pool name**: Warehousexx, where xx are your initials.

Update last image, as attached. 
![Synapsebasicstab](https://user-images.githubusercontent.com/11367710/99557796-4ed3fb00-2980-11eb-95fe-a847a05fc1e1.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved
