### ISSUE TITLE
Lab 6, Exercise 2, Tasks 1, Step 3 - update settings order and screenshot

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#126]
Lab 6, Exercise 2, Tasks 1, Step 3 - update settings order and screenshot, as attached.  

Change step 3 from:
3. In the Create Namespace blade, type out the following options:

Name: xx-phoneanalysis-ehn, where xx are your initials
Pricing Tier: Standard
Subscription: Your subscription
Resource group: awrgstudxx
Location: select the location closest to you
Throughput Units: 20

Leave other options to their default settings

To:  
3. In the Create Namespace blade, type out the following options:

Subscription: Your subscription
Resource group: awrgstudxx
Name: xx-phoneanalysis-ehn, where xx are your initials
Location: select the location closest to you
Pricing Tier: Standard
Throughput Units: 20

Leave other options to their default settings

![eventhubbasicstab](https://user-images.githubusercontent.com/11367710/99588056-46db8180-29a7-11eb-89e4-5f02751bb5aa.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved
