### ISSUE TITLE
Lab 5, Ex 3, Task 2 & 3

### ISSUE THREAD

**Issue by tokleine** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#128]
It seems that the currently supplied TSQL statements do not work as expected. The one for task 2 throws an error, stating incorrect syntax. Both the tsql statement from the lab files, as well as my own (see screenshot) do not work as expected. 

![image](https://user-images.githubusercontent.com/57629009/102772013-1c565d00-4387-11eb-89c9-0c14061f31e2.png)
![image](https://user-images.githubusercontent.com/57629009/102771981-11033180-4387-11eb-8996-82234cfaefa9.png)

Similarly for task 3 the provided statements do not work, see screenshot.
![image](https://user-images.githubusercontent.com/57629009/102772258-7820e600-4387-11eb-8523-21c3c099c3ae.png)
![image](https://user-images.githubusercontent.com/57629009/102772286-840ca800-4387-11eb-9877-2865ee6e6aae.png)

I am using SSMS 18.7.1.

**Comment by tokleine** [comment]
Just saw that this issue was potentially fixed in the latest PR (#127 )

**Comment by tokleine** [comment]
It appears however, that the same problem exists in the synapse web interface: 
![image](https://user-images.githubusercontent.com/57629009/102773954-58d78800-438a-11eb-9e4e-1eafe0b2c204.png)

**Comment by ctesta-oneillmsft** [comment]
resolved
