### ISSUE TITLE
CREATE DATABASE statement is not supported in a Synapse workspace. To create a SQL pool, use the Azure Synapse Portal or the Synapse REST API.

### ISSUE THREAD

**Issue by pawel-f** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#129]
When trying to execute the statement: CREATE DATABASE DWDB COLLATE SQL_Latin1_General_CP1_CI_AS
(
    EDITION             = 'DataWarehouse'
,   SERVICE_OBJECTIVE   = 'DW100C'
,   MAXSIZE             = 1024 GB
);
from the https://github.com/MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution/blob/master/instructions/dp-200-05_instructions.md

I got:  ![image](https://user-images.githubusercontent.com/11706500/103380934-91920280-4aea-11eb-918c-099d01ae8430.png)

**Comment by puneetsharma04** [comment]
Even i am facing the same issue when i tried creating the 'DWDB' today.

**Comment by ctesta-oneillmsft** [comment]
Hello

Thanks for this feedback. 

We have placed a workaround in the instructions and working with the PG on this issue

Thanks

Chris
