### ISSUE TITLE
Module 6 Managed Identity v Connection String

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#137]
When setting up the blob store output, new option for authentication default to Managed Identity but needs to changed to Connection string for this lab.

![image](https://user-images.githubusercontent.com/36226388/108195951-6aca7280-7110-11eb-9470-beb737712d26.png)

**Comment by Kaijisse** [comment]
Updated, so closing this issue.
