### ISSUE TITLE
Add pause instructions to new Synapse Excercises

### ISSUE THREAD

**Issue by juggehassel** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#138]
Lab 5 - Working with Relational Data Stores in the Cloud
I think it would be great to add instructions in this excercise for:
1) Always have the lowest performance on dedicated SQL pools (DW100)
2) Add clear instructions at the end of the excercise (as it has been before) to PAUSE the dedicated SQL pool.

This will be a problem if the course is divided into smaller parts and the teacher forgets to remind about this.

**Comment by Kaijisse** [comment]
For lab 5, instruction to pause the dedicated sql pool has been added (see screenshots). 
![image](https://user-images.githubusercontent.com/38757647/119988709-ac4ba300-bfc6-11eb-91e6-fd199028db44.png)

![image](https://user-images.githubusercontent.com/38757647/119988493-773f5080-bfc6-11eb-9a4f-f68cacf4e383.png)

I also added to slide the performance to DW100, see screenshot:
![image](https://user-images.githubusercontent.com/38757647/119989152-23813700-bfc7-11eb-9480-b9b7c6411663.png)

In relation to allowing Azure services and resources to access the workspace, this is set to on, as per instructions (see screenshot):
![image](https://user-images.githubusercontent.com/38757647/119989298-4f042180-bfc7-11eb-96ca-fa016d1ff4a0.png)

I also added pause as well as resume instructions at the beginning of lab 7, see screenshot:
![image](https://user-images.githubusercontent.com/38757647/119989615-ad310480-bfc7-11eb-9a47-17a4c87a0b7b.png)

Closing these issues.
