### ISSUE TITLE
Lab 3 - Exercise 3 - Task 5 - Azure update change lab process

### ISSUE THREAD

**Issue by arnaudbc** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#141]
Still reference File system 

//Read JSON data in Azure Data Lake Storage Gen2 file system

val df = spark.read.json("abfss://<file-system-name>@<storage-account-name>.dfs.core.windows.net/preferences.json")

Should refer to container (And it's not doing well instead)

**Comment by ctesta-oneillmsft** [comment]
unable to reproduce, and this worked. Checked with two environments and two seperate testers
