### ISSUE TITLE
Lab 7, Exercise 3, Task 1, reorder steps 1 and 2

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#142]
The data flow debug option is not available until you add a data flow to the workspace, so the steps need to be reordered.

Also, step 3 could do with more detailed instructions.

1. Add a data flow activity. …

2. Turn on data flow debug. …

3. Select the data flow activity in the pipeline workspace. In the lower pane, select the Settings tab then click +New.

**Comment by Kaijisse** [comment]
Updated. Closing this issue.
