### ISSUE TITLE
Lab 7, Exercise 4, Task 3 and Task 5 (there is no Task 4)

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#143]
The ADF Workspace editor has changed since these instructions were written. The left-hand menu now has Author, Monitor and Manage as three separate sections.

Select the Manage item in the left hand menu to create the linked service (steps 3 to 6 in task 3). Select the Author item to create the pipeline (task 5).

**Comment by Kaijisse** [comment]
Updated. Closing this issue.
