### ISSUE TITLE
Lab 4 issue with query for task 3 step 4

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#148]
In Github this looks correct but in the lab it shows up like the text below

SELECT
    1. []id,
    1. []manufacturer,
    1. []description
FROM Products p
WHERE p.id ="1"

**Comment by TesterTesterson1004** [comment]
This issue should now be corrected, although it was a presentation problem within an ALH rather then a problem w/the code here.  Can you refresh on your side and see if you see it displaying properly now?

![image](https://user-images.githubusercontent.com/49700217/118067561-aa8ea800-b355-11eb-838f-4b48040417ce.png)

**Comment by Kaijisse** [comment]
Closing this issue as resolved.
