### ISSUE TITLE
Lab 06 Twitter and TwitterClient from LOD

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#15]
From LearnOnDemand it is not possible to access the Twitter developer website. Also the TwiiterClient doesn't receive any tweets. Better to configure the Twitter Developer App in a separate browser (outside LOD) and download the TwitterClient on the students laptop. Then it will work.

I guess traffic is blocked. Accesing twitter.com from different browsers is blocked by FortiGuard.

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback, It will be addressed this week

**Comment by ctesta-oneillmsft** [comment]
Yes the traffic is blocked and we have no control of this

**Comment by trayhumphrey** [comment]
> From LearnOnDemand it is not possible to access the Twitter developer website. Also the TwiiterClient doesn't receive any tweets. Better to configure the Twitter Developer App in a separate browser (outside LOD) and download the TwitterClient on the students laptop. Then it will work.
> I guess traffic is blocked. Accesing twitter.com from different browsers is blocked by FortiGuard.

@molenaar Were you able to run the Twitter WPF client off the LOD machine? I could not, either using the supplied Twitter keys or my own (after a lengthy process of establishing a Twitter Dev account). I downloaded the files locally, ran the app, and nothing happens. My access is not firewall related.

@ctesta-oneillmsft Is there a plan to replace this lab with something that shows the value of Stream Analytics? It seems like a big disappointment to students to get this far and be told, "Yeah it doesn't work."

**Comment by PekkaGH** [comment]
I'm running twitter wpf client from my own laptop and it used to work fine (last time in May), but now it doesn't work anymore...? And I have course on this after two weeks so have to find out some workaround!
Any ideas?

**Comment by trayhumphrey** [comment]
@PekkaGH, I tried the TwitterWPFClient from my own laptop as well just this week. It starts, but never shows data and never shows an error. I have tried both the included Twitter keys and even went through the lengthy process of setting up a Twitter Dev account to get my own keys. Nothing I've tried works. 

The developer is mentioned in the app, but who knows when it was written and whether the app is being maintained. If you hear or think of any workaround, I'd love to know.

**Comment by Derekp20** [comment]
I do not use the twitter example when teaching, because of issues in getting it to work. Instead I demonstrate (and get the students to do it with me) an example using the Sensor Event Generator available from GitHub. Create an Event hub and stream analytics. Output to a SQL database. I also demonstrate output to PowerBI . Most really like this. I have had only one person in 2 courses that has tried the twitter lab (and he couldn't get it to work). There is a video out there of this being demonstrated (but cann't find it just now!)

**Comment by Derekp20** [comment]
Found it https://www.youtube.com/watch?v=OGZ2-1cFLjE

**Comment by PekkaGH** [comment]
@Derekp20 , you saved my day! Thanks! That's what I'll be doing next time in my course.

**Comment by trayhumphrey** [comment]
Indeed! Many thanks, @Derekp20! I'll definitely be integrating this.

**Comment by dpapkin** [comment]
Thanks for the youtube video. Will have to show it next week. Any plans to update our lab to something workable? Not sure how well received it will be if I say "the lab doesnt work, sorry."

**Comment by Derekp20** [comment]
Look at Lab 6B on https://github.com/Derekp20/DP200
It needs some slight editing, but my delegates managed to follow it.

**Comment by dpapkin** [comment]
Thanks for the lab, appreciate it.

I updated lab 7 to match the changes in the portal and fixed some typos. I have attached it, if you are interested.


DP



________________________________
