### ISSUE TITLE
Access to the original training video:

### ISSUE THREAD

**Issue by cdataminer** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#16]
I am trying to gain access to the EDX training videos, but they are not available anymore. Does anyone know where I can find the training video?
thank you
Tomas Santandreu Polanco

**Comment by vitaly-livshits** [comment]
This repo is dedicated to the DP-200 instructor-led course. Are you perhaps referring to a self-guided learning program instead?

**Comment by cdataminer** [comment]
Hi

Thank you for the replied and yes I looking for the self-guided learning program. Any ideas where I might be able to get access to the contents.

Thank you
Tomas  Santandreu

________________________________

**Comment by vitaly-livshits** [comment]
Most of Microsoft's self-guided learning content is now at Microsoft Learn:

https://docs.microsoft.com/en-us/learn/
