### ISSUE TITLE
Lab 5 Password Incorrect

### ISSUE THREAD

**Issue by dougdavis** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#17]
The password in _dp-200-05_instructions.md Exercise 3 , Task 1 , Item 1, Line 166_ has a different password for _xxsqladmin_ than the once specified in the Create Database task. 

The corrected line should read:
    - Password: **Pa55w.rd**

I tried to submit a PR but ran into a permission issue.

**Comment by vitaly-livshits** [comment]
This is still an issue and it's indeed confusing students.

@ctesta-oneillmsft, can this be fixed? Also, can PR permissions be opened up?

**Comment by ctesta-oneillmsft** [comment]
Passworf updated
