### ISSUE TITLE
Lab 2 Ex 3 Task 2 

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#2]
Additional instructions needed to Add Azure Account to Azure Storage Explorer prior to:  Lab 2 Ex 3 Task 2

In Azure Storage Explorer, Click Add Account icon > Select Add an Azure Azure Account radio button > Click Sign in.. button > enter account name and password > Click Sign in button
   
Task 2: Upload data files to the data container of the Data Lake Gen II Storage Account.
1.	In Azure Storage Explorer, click on the arrow to expand your subscription.  <== not unless you add the account first

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback, It will be addressed this week

**Comment by ctesta-oneillmsft** [comment]
Have added instructions at the end of the  previous task on how to Add Azure Account to Azure Storage Explorer :

1. On completion of the installation, ensure that the checkbox next to **Launch Microsoft Azure Storage Explorer** is selected and then click **Finish**. Microsoft Azure Storage Explorer opens up and lists your subscriptions.

1. In Storage Explorer, select **Manage Accounts** to go to the **Account Management Panel**.

1. The left pane now displays all the Azure accounts you've signed in to. To connect to another account, select **Add an account**

1. If you want to sign into a national cloud or an Azure Stack, click on the Azure environment dropdown to select which Azure cloud you want to use. Once you have chosen your environment, click the **Sign in...** button.

1. After you successfully sign in with an Azure account, the account and the Azure subscriptions associated with that account are added to the left pane. Select the Azure subscriptions that you want to work with, and then select **Apply**. The left pane displays the storage accounts associated with the selected Azure subscriptions.

**Comment by ctesta-oneillmsft** [comment]
fix will be deployed friday
