### ISSUE TITLE
Lab 7

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#20]
Objectives are from Lab 6, need to be corrected.

Ex 1 Refers to Lab6 files and streaming data. Needs to be corrected to refer to Lab 7 files

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft  Can this please be fixed?

**Comment by VitalyMCT** [comment]
Further to the above, the entire Exercise 1 seems to be a copy & paste of that exercise in Lab 6. Presumably, the goal is to explain how to apply ADF to implement the requirements in the scenario. If so, the corresponding files are also missing from \Starter and \Solution files.

**Comment by ctesta-oneillmsft** [comment]
Lan replaced
