### ISSUE TITLE
Module 3 | Ex 3 > Task 3 > Step 7

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#24]
In Azure, this has changed from "saved" to "Add". It should read as follows please:

"Provide a description of DL Access Key, and a duration of In 1 year for the key. When done, click **Add**."

Thank you!

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
@VitalyMCT I dont repsond to tags like this

**Comment by ctesta-oneillmsft** [comment]
@mreherefortea  this has been updated
