### ISSUE TITLE
Lab 5 distribution = replicate seems wrong

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#25]
Unable to use  DISTRIBUTION  in New Query red underline under REPLICATE and error msg " incorrect syntax near distribution "

![image](https://user-images.githubusercontent.com/24426530/66825561-10019380-ef7d-11e9-91fa-1fed34072798.png)

thanks

Class is next week!

**Comment by dpapkin** [comment]
Hi,

In our prior Query, we create the DWDB database.  The instructions need to specify that this query needs to be ran against the created **DWDB** database specifically.

Can you please  update the Lab instructions in the 3 places  we create a table 
 1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.
CHANGE TO
1. In **SQL Server Management Studio**, in Object Explorer, right click **DWDB** and click on **New Query**. ?

The class is monday and is 20 PAX  and is sponsored by Microsoft for a HUGE potential Azure client

Thanks for your help

David Papkin
MCT

## Task 3: Create SQL Data Warehouse tables.

1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.

    >**Note**: If you are unfamiliar with Transact-SQL, there is a script in the Allfiles\Solution\DP-200.5\folder named **Exercise3 Task3Step2 script.sql**. It contains the bulk of the code required to create the tables, but you do have to complete the code by selecting the distribution type to use for each table 

1. Create a table named **dbo.Users** with a **clustered columnstore** index with a distribution of **replicate** with the following columns:

    | column name | data type | Nullability|
    |-------------|-----------|------------|
    | userId | int | NULL|
    | City | nvarchar(100) | NULL|
    | Region | nvarchar(100) | NULL|
    | Country | nvarchar(100) | NULL|

1. In **SQL Server Management Studio**, click on **Execute**.

1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.

1. Create a table named **dbo.Products** with a **clustered columnstore** index with a distribution of **round robin** with the following columns:

    | column name | data type | Nullability|
    |-------------|-----------|------------|
    | ProductId | int | NULL|
    | EnglishProductName | nvarchar(100) | NULL|
    | Color | nvarchar(100) | NULL|
    | StandardCost | int | NULL|
    | ListPrice | int | NULL|
    | Size | nvarchar(100) | NULL|
    | Weight | int | NULL|
    | DaysToManufacture | int | NULL|
    | Class | nvarchar(100) | NULL|
    | Style | nvarchar(100) | NULL|

1. In **SQL Server Management Studio**, click on **Execute**.

1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.

1. Create a table named **dbo.FactSales** with a **clustered columnstore** index with a distribution of **Hash** on the **SalesUnit** with the following columns:

    | column name | data type | Nullability|
    |-------------|-----------|------------|
    | DateId | int | NULL|
    | ProductId | int | NULL|
    | UserId | int | NULL|
    | UserPreferenceId | int | NULL|
    | SalesUnit | int | NULL|

**Comment by VitalyMCT** [comment]
In addition to updates in David's comments, the instructions should also tell students not to worry about the red line that SSMS puts under "DISTRIBUTION". That's just Intellisense being unaware of this Azure Synapse TSQL keyword.

**Comment by ctesta-oneillmsft** [comment]
I have added a graphic for clarity for one of the table creation statment. Any more would give the students the answer. This lab has also been updated to Azure Synapse Analytics
