### ISSUE TITLE
Lab 7  Ex2 Task 2 DeptDatabaseesxx not found

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#26]
I dont see DeptDatabsesxx from the dropdownlist

In Module 5 Ex 1 task 1  The database name needs to be specified, even though we picking "Sample" under additional settings.  this is **Required** . Is left out of the instructions or perhaps interface has changed, maybe before it auto populated the name. I am not sure if needs to be **DeptDatabasesxx** to be compatible with Module 7 or AdventureworksLT. 

DP

Module 7 lab

Task 2: Create an input linked services
In the Azure portal, a message is returned to state that the Azure Data Factory installation has completed successfully, click Go to resource.

In the xx-data-factory screen, click on Author & Monitor. Another tab opens up to author an Azure Data Factory solution.

In the Get started page, select the Copy Data tile to launch the Copy Data tool:

In the Properties page, specify CopyFromSQLToSQLDW for the Task name field, and select Next:

In the Source data store page, complete the following steps and then click on Next:

click + Create new connection:
Select Azure SQL Database from the gallery, and select Continue.
In the New Linked Service (Azure SQL Database) page, select your server name sqlservicexx and database named DeptDatabasesxx from the dropdown list, and specify the username and password. Click Test Connection connection to validate the settings, and then click Finish.

DP

**Comment by ctesta-oneillmsft** [comment]
Lab updated to be AdventureworksLT
