### ISSUE TITLE
Lab 5 Ex 1 Task 1 SQL database name not specified

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#27]
In Module 5 Ex 1 task 1 The database name needs to be specified, even though we picking "Sample" under additional settings. this is Required . Is left out of the instructions or perhaps interface has changed, maybe before it auto populated the name. I am not sure if needs to be DeptDatabasesxx to be compatible with Module 7 or AdventureworksLT.

I have selected Sample but when I go back to the Basic screen, the name must still be filled in

![image](https://user-images.githubusercontent.com/24426530/66897832-6d9fe980-f02a-11e9-913f-05502e8406a2.png)

![image](https://user-images.githubusercontent.com/24426530/66897900-92945c80-f02a-11e9-8c8d-b601c7b1bc32.png)

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
@VitalyMCT  I respectfully ask not to tag me unless you have a comment

@dpapkin Instructions have been updated. Thanks
