### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#29]
Hello Team:

While investigating an issue presented by an instructor the following errors were found in the directions that I was hoping you could amend please:

Lab 5 > Ex 1 > Task 1 > Step 4:

When sample is selected, it does not auto-populate the database name under the basics tab. A step needs to be added please to input the name of AdventureworksLT please. 

Lab 5 > Exercise 2 > Task 3  > Step 1:

The directions request you run a new query against swlservicexx and not the 'DWDB' database created with the prior query. If DWDB is not selected, the query cannot execute properly because DISTRIBUTION is not recognized.  The directions need to specify to execute the new query against DWDB please. 

Lab 5 >  Ex 3 > Task 1 > Step 5:

P@ssw0rd was updated to Pa55w.rd in earlier steps but needs to be updated here as well please. 

Lab 7 >  Ex 2 > Task 2 > Step 5:

The directions request you select DeptDatabasesxx.  Reviewing the change log for Lab 5 (where our databases are created), the naming convention of DeptDataBasesxx was changed to to selecting the sample AdventureworksLT.  When the end-user gets to this point, there is no DeptDatabasexx and naming will need to be updated here to avoid confusion please. 

Thank you!

**Comment by vitaly-livshits** [comment]
Thanks @mreherefortea!

@ctesta-oneillmsft, can these be incorporated into master?

**Comment by ctesta-oneillmsft** [comment]
Lab updated
