### ISSUE TITLE
Lab 4 out of date with regards to Cosmos functionality

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#3]
Working through Module 4 it appears that Cosmos has moved on since this was written, with many small things such as Collections now being Containers now, Documents being Items, and a couple of larger issues later on with VS Code functionality making this a very difficult lab to complete with the LAK.  There are far too many edits necessary to make this representative of the current Cosmos experience to list here.  I would request that an SME be asked to run though this and make edits as necessary.

**Comment by markfitzqa** [comment]
**Exercise 2 Task 1**
1. In the Azure portal, in the awcdbstudxx - Quick start screen, click on the Overview option in the blade.

2. In the awcdbstudxx screen, click + Add Container. This opens up Data Explorer with the Add Container screen.

3. In the Add Collection screen, create a Products database with a collection named Clothing with the following settings:
- Database id: Products
- Container id: Clothing
- Partition key: /productId
- Leave the remaining options with their default values

4. In the Add Container screen, click OK

**Exercise 2 task 2 (steps 2-4)**
2. In the SQL API pane, expand Clothing and click on Items. A new document appears with a sample JSON that you will now replace.

3. In the Documents pane, click on the icon for New Item.

4. Copy the following code and paste it into the Items tab:

**Exercise 3 Step 1 Step 8**
Step 8 not required as it is done later (step 11)

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback, It will be addressed this week

**Comment by ctesta-oneillmsft** [comment]
A revioew of this lab has been complete with updates. In addition exercise 3 is now an optional exercise at the end, so is now exercise 4. Exercise 4 has now become exercise 3. Based on feedback from MCTs, they have felt that the lab creating a .Net app is a step too far for this course. Leaving the content in, but it is an optional exercise
