### ISSUE TITLE
Databricks cores incompatable with free trial. 

### ISSUE THREAD

**Issue by queenlasql** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#30]
Suggestion: Since this is part of Microsoft learning, is it possible to increase the cores on the free 30 day trial so that the data bricks portion can be completed? I can't complete the labs on a trial free account - and I don't want to get charged for playing around with new technology... I get the following Error: 'The operation couldn't be completed as it results in exceeding quota limit of Core. Maximum allowed: 4, Current in use: 4, Additional requested.'

**Comment by Derekp20** [comment]
You are correct the free trial accounts from Azure don't work. As an MCT you can get an Azure Pass for prep and teaching. Details are under resources on MCT Central site, as well as the Courseware forums that answer many questions about this course.

**Comment by vitaly-livshits** [comment]
The Azure Free Trial has many limitations that make it incompatible with the latest role-based courses. 

I don't think that's necessarily an issue that needs to be addressed. Both the MCT instructor and the students get Azure Passes. These function without such service provisioning limitations and thus work fine for this course.
