### ISSUE TITLE
Lab 2 Ex 3 and 4 "File Systems" has become "Storage" or "Containers"

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#32]
## Explanation
Within Azure Data Lake Gen II (hierarchical) storage accounts, some of the Azure UI labels that formerly said **File Systems** now say either **Storage** or **Containers** .

Text to be replaced and the replacement are formatted in syntax highlighting below.
### Currently reads:
2. In the awdlsstudxx screen, where xx are your initials, under the Services click Data Lake ``` Gen2 file systems. ```
### Suggested change:
2. In the awdlsstudxx screen, where xx are your initials, under the Services click Data Lake ``` Storage``` .

### Currently reads:
3. In the awrgstudxx - ``` File systems```  screen, at the top left, click on the + File systems button.
### Suggested change:
3. In the awrgstudxx - ``` Containers```  screen, at the top left, click on the + File systems button.

### Currently reads:
Note: The creation of the file system is immediate and will appear in the list of the awdlsstudxx - ``` File systems``` screen.
### Suggested change:
Note: The creation of the file system is immediate and will appear in the list of the awdlsstudxx - ``` Containers ``` screen.

### Currently Reads:
In the Azure portal, in the awdlsstudxx - ``` File systems``` screen, click on the data item in the list.
### Suggested change:
In the Azure portal, in the awdlsstudxx - ``` Containers``` screen, click on the data item in the list.

**Comment by vitaly-livshits** [comment]
This is indeed confusing to students, especially those new to Azure and thus without historical naming background.

@ctesta-oneillmsft, can this please be patched up in the instructions?

**Comment by ctesta-oneillmsft** [comment]
lab updated with graphics to aif students
