### ISSUE TITLE
dp-200-07

### ISSUE THREAD

**Issue by queenlasql** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#34]
Not a show stopper, but Task 2:  -> select your server name **sqlservicexx** and database named **DeptDatabasesxx** 

we never created this database. Perhaps we were supposed to rename adventureworksLT to deptDatabases in -05 lab?

**Comment by Derekp20** [comment]
This is a revised version of the instructions. It used to have the database name, but not to select the sample database, now it the other way round. Since I had amended my own copy, I hadn't notice this error. There should be a line with Database name: deptdatabasexx.

**Comment by Derekp20** [comment]
Sorry, that should be in lab 5 exercise 1, task 4

**Comment by dpapkin** [comment]
Already mentioned in lab corrections to use adventureworksLT.is there a reason to rename it? Issue is that the interface has changed,previously selecting Sample would auto populate adventureworksLT as the name

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctesta-oneillmsft** [comment]
renamed to  AdventureworksLT. Thanks
