### ISSUE TITLE
Lab 3 Ex 2 Task 3 Databricks Runtime Version - 5.1 is gone, perhaps choose default instead

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#35]
Since it won't be possible for the courseware instructions to keep up with versions available in Azure (even on Github), would it be better to have the student choose whichever is the default selected runtime version? Or alternatively, one of the LTS versions, which will remain in the list longer?

I'm wondering if a student could run into any problems if they pick an incorrect runtime version.  It doesn't seem likely to me given the limited scope of tasks in the course.

**Comment by vitaly-livshits** [comment]
Agreed, either of these two options would work. 

My vote would be for tying instructions to a specific LTS version. That would allow everything to be verified for a specific point in time and thus be guaranteed to work for students in the classroom.

@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
Lab updated to a new version.
