### ISSUE TITLE
Typo in DP-200-Lab03-Ex01.docx   

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#36]
Line 2 in the Word document says "Lab 2"; it should be "Lab 3".

The error occurs in both the Starter and Solution folders:
DP-200-Implementing-an-Azure-Data-Solution/Labfiles/Starter/DP-200.3
DP-200-Implementing-an-Azure-Data-Solution/Labfiles/Solution/DP-200.3

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
Thanks @davidcwalls . Resolved
