### ISSUE TITLE
Lab 3 Ex 3 Task 3 Step 4 uses a live, non-Microsoft website for Redirect URI

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#37]
The link currently in the instructions is **https://adventureworks.org/exampleapp**

It should presumably be **https://adventure-works.com/exampleapp**

**Comment by Derekp20** [comment]
Maybe, but it has no meaning so is not important to make the lab work.

**Comment by davidcwalls** [comment]
It's bad practice, and I believe it violates MS policy, so it should be changed.
If it has no meaning, we might be better off without it.

**Comment by ctesta-oneillmsft** [comment]
Resolved. Thanks for the catch
