### ISSUE TITLE
Lab 7 - Ensure data factory can connect to your Azure SQL Database by allowing in Firewall

### ISSUE THREAD

**Issue by dave-007** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#38]
Review the Developer terms and click on Create. A new page will appear with the title of you application name.

Click on the page tab named Keys and tokens

**Comment by dave-007** [comment]
Working with Data Factort, in the step to add a Source connection for the 'Copy data' step, this fails when I test connection, unless I first configure my Azure SQL Server under 'Firewalls and virtual networks' to allow Azure services and resources to access this server'
![image](https://user-images.githubusercontent.com/240789/67939370-caadaa80-fba7-11e9-982a-7f78d3620c3e.png)

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
The instructions connect to Azure Synapse Analytics, not SQL Database
