### ISSUE TITLE
Twitter infrequently approves developer account applications

### ISSUE THREAD

**Issue by sanpietro** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#39]
I have taught several courses where students were required to create Twitter developer accounts and more often than not, regardless of the verbiage that was propose, Twitter denied their applications. Therefore, this is no longer a suitable use case. I would propose swapping this out with Reddit, which has proven in my experience to be far more student-friendly.

**Comment by davidcwalls** [comment]
I agree that Twitter (or really any third-party service that requires registration) is problematic for this class. I like Derekp20's suggestion to use an event generator program as the source - it allows for a much more controllable environment and students don't have to waste time trying to get an outside service working. It also allows the labs to run in LearnOnDemand environments.

**Comment by ctesta-oneillmsft** [comment]
Twitter lab archived and lab replaced
