### ISSUE TITLE
Lab 5, Exercise 3, Task 3 Missing SQL scripts

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#4]
This task asks the user to create a number of tables using SQL commands.  While the table templates are here, the SQL script necessary to create the tables is not present in the Lab Answer Key.

**Comment by markfitzqa** [comment]
Agreed, may be create a template included in the lab files to get the delegates to complete the distribution and indexing within the WITH clause.

-- Desired scripts
**Exercise 3 Task 3 Step 2**
CREATE TABLE dbo.Users(
	userId int null,
	City nvarchar(100) null,
	Region nvarchar(100) null,
	Country nvarchar(100) null
) WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = REPLICATE
);
GO

**Exercise 3 Task 3 Step 5**
CREATE TABLE dbo.Products(
	ProductId int null,
	EnglishProductName nvarchar(100) null,
	Color nvarchar(100) null,
	StandardCost int null,
	ListPrice int null,
	Size nvarchar(100) null,
	Weight int null,
	DaysTomanufacture int null,
	Class nvarchar(100) null,
	Style nvarchar(100) null
) WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = ROUND_ROBIN
);
GO

**Exercise 3 Task 3 Step 8**
CREATE TABLE dbo.FactSales(
	DateId int null,
	ProductId int null,
	UserId int null,
	UserPreferenceId int null,
	SalesUnit int null
) WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(SalesUnit)
);
GO

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback, It will be addressed this week

**Comment by ctesta-oneillmsft** [comment]
script file has been added to the Labfiles solution folder for module 5

**Comment by dpapkin** [comment]
I am unable to use the word DISTRIBUTE in my SQl query. DISTRIBUTION has red underline and  error msg incorrect syntax near distribution.  Any ideas? I have redone the lab twice

CREATE TABLE dbo.Users(
userId int null,
City nvarchar(100) null,
Region nvarchar(100) null,
Country nvarchar(100) null
) WITH (
CLUSTERED COLUMNSTORE INDEX,
DISTRIBUTION = REPLICATE
);
GO
--Exercise 3 Task 3 Step 5
CREATE TABLE dbo.Products(
ProductId int null,
EnglishProductName nvarchar(100) null,
Color nvarchar(100) null,
StandardCost int null,
ListPrice int null,
Size nvarchar(100) null,
Weight int null,
DaysTomanufacture int null,
Class nvarchar(100) null,
Style nvarchar(100) null
) WITH (
CLUSTERED COLUMNSTORE INDEX,
DISTRIBUTION = ROUND_ROBIN
);
GO

--Exercise 3 Task 3 Step 8
CREATE TABLE dbo.FactSales(
DateId int null,
ProductId int null,
UserId int null,
UserPreferenceId int null,
SalesUnit int null
) WITH (
CLUSTERED COLUMNSTORE INDEX,
DISTRIBUTION = HASH(SalesUnit)
);
GO
![image](https://user-images.githubusercontent.com/24426530/66825385-c0bb6300-ef7c-11e9-958c-6d562ed0266c.png)

**Comment by markfitzqa** [comment]
Sorry those scripts worked in my environment.  Distribute is only available in the Azure Data Warehouse.  I had the same issue when I first did the labs due to not being within the correct database, as we have both a normal SQL db and a DW on the same SQL Server.

Try that and get back to me with more details as the issue.

Fitz

**Comment by dpapkin** [comment]
Hi Mark,

Thanks for the prompt reply 🙂🙂. Yep, I needed to right click on the DB and run New Query from there.

Not sure why the sql command Exercise3 Task3Step2 script.sql isn't filled in, just has DISTRIBUTION = ________

Would be very helpful if the solution is complete like below. Can we get that updated?

-- Exercise 3 Task 3 Step 2 script
-- Replace the underline with the distribution type​
CREATE TABLE dbo.Users(​
userId int null,​
City nvarchar(100) null,​
Region nvarchar(100) null,​
Country nvarchar(100) null​
) WITH (​
CLUSTERED COLUMNSTORE INDEX,​
DISTRIBUTION = REPLICATE
);​
GO​
--Exercise 3 Task 3 Step 5​
CREATE TABLE dbo.Products(​
ProductId int null,​
EnglishProductName nvarchar(100) null,​
Color nvarchar(100) null,​
StandardCost int null,​
ListPrice int null,​
Size nvarchar(100) null,​
Weight int null,​
DaysTomanufacture int null,​
Class nvarchar(100) null,​
Style nvarchar(100) null​
) WITH (​
CLUSTERED COLUMNSTORE INDEX,​
DISTRIBUTION = ROUND_ROBIN​
);​
GO​
--Exercise 3 Task 3 Step 8​
CREATE TABLE dbo.FactSales(​
DateId int null,​
ProductId int null,​
UserId int null,​
UserPreferenceId int null,​
SalesUnit int null​
) WITH (​
CLUSTERED COLUMNSTORE INDEX,​
DISTRIBUTION = HASH(SalesUnit)​
);​
GO​


DP

**Comment by dpapkin** [comment]
What’s weird is that DISTRIBUTION = REPLICATION doesn’t work but DISTRIBUTION = REPLICATE works. Also, Why is REPLICATE pink color in SSMS?

I am teaching next week!

Thanks a lot Fitz

DP

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dpapkin** [comment]
Hi Mark,

Yep, right-clicking the DWDB did the trick,

Can you get the github instructions updated this week please?

I am teaching this class for MS sponsored event next week and is HUGE class, will be chaos. THE LODS DL the labs directly from Github when the students run the VMs, so I cant update the instructions manually,

I have ahowed the suggested change, is quite minor actually

Thanks for your help

David

In our prior Query, we create the DWDB database.  The instructions need to specify that this query needs to be ran against the created **DWDB** database specifically.

Can you please  update the Lab instructions in the 3 places  we create a table
 1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.
CHANGE TO
1. In **SQL Server Management Studio**, in Object Explorer, right click **DWDB** and click on **New Query**. ?

The class is monday and is 20 PAX  and is sponsored by Microsoft for a HUGE potential Azure client

Thanks for your help

David Papkin
MCT

## Task 3: Create SQL Data Warehouse tables.

1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.

    >**Note**: If you are unfamiliar with Transact-SQL, there is a script in the Allfiles\Solution\DP-200.5\folder named **Exercise3 Task3Step2 script.sql**. It contains the bulk of the code required to create the tables, but you do have to complete the code by selecting the distribution type to use for each table

1. Create a table named **dbo.Users** with a **clustered columnstore** index with a distribution of **replicate** with the following columns:

    | column name | data type | Nullability|
    |-------------|-----------|------------|
    | userId | int | NULL|
    | City | nvarchar(100) | NULL|
    | Region | nvarchar(100) | NULL|
    | Country | nvarchar(100) | NULL|

1. In **SQL Server Management Studio**, click on **Execute**.

1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.

1. Create a table named **dbo.Products** with a **clustered columnstore** index with a distribution of **round robin** with the following columns:

    | column name | data type | Nullability|
    |-------------|-----------|------------|
    | ProductId | int | NULL|
    | EnglishProductName | nvarchar(100) | NULL|
    | Color | nvarchar(100) | NULL|
    | StandardCost | int | NULL|
    | ListPrice | int | NULL|
    | Size | nvarchar(100) | NULL|
    | Weight | int | NULL|
    | DaysToManufacture | int | NULL|
    | Class | nvarchar(100) | NULL|
    | Style | nvarchar(100) | NULL|

1. In **SQL Server Management Studio**, click on **Execute**.

1. In **SQL Server Management Studio**, in Object Explorer, right click **sqlservicexx.database.windows.net** and click on **New Query**.

1. Create a table named **dbo.FactSales** with a **clustered columnstore** index with a distribution of **Hash** on the **SalesUnit** with the following columns:

    | column name | data type | Nullability|
    |-------------|-----------|------------|
    | DateId | int | NULL|
    | ProductId | int | NULL|
    | UserId | int | NULL|
    | UserPreferenceId | int | NULL|
    | SalesUnit | int | NULL|



________________________________

**Comment by dpapkin** [comment]
When I discover errors, sould I  I  fix the docs, how to I post them? Whats the right way?

Thx

David

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by markfitzqa** [comment]
Best to raise issues on the github repository.  The content developers do check these regularly.  If you also post into the MCT courseware forum the issue will be raised for the larger MCT community.  Sometimes an issue for one area can be fixed by an MCT from another.

Fitz

**Comment by MartinDBakerCDW** [comment]
Well, this is still happening with HASH(SalesUnit).....

Msg 102, Level 15, State 1, Line 8
Incorrect syntax near 'CLUSTERED'.
