### ISSUE TITLE
DP-200 Lab 7 Ex 2 Task 1 Step 2

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#40]
DP-200 Lab 7 Ex 2 Task 1 Step 2 "Leave other options to their default settings" will result in an error unless you uncheck Enable GIT. Also, the recommendation to differ global naming by prefixing with xx (your initials) does not suffice for all students.

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
Thanks @TammySmithMCT  Resolved
