### ISSUE TITLE
Lab 5 Ex 2 Task 1 Step 2

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#41]
SQL Data Warehouse is now Azure Synapse Analytics. Search for SQL does show it, but this may change. I guess the whole module will need a rewrite soon!

Same applies in Lab 7 for the Destination Service.

**Comment by vitaly-livshits** [comment]
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
updated and resolved
