### ISSUE TITLE
Lab 2 - Conflicting instructions for Exercise 2

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#45]
Introduction asks to create 2 containers:

![image](https://user-images.githubusercontent.com/1765732/70855324-1a65de00-1e97-11ea-8f8a-37780d89c475.png)

The details (under Task 3) ask to create 3 containers:

![image](https://user-images.githubusercontent.com/1765732/70855328-26ea3680-1e97-11ea-9660-d33f4161eada.png)

Which one is correct?

**Comment by ctesta-oneillmsft** [comment]
Updated. Thanks @VitalyMCT
