### ISSUE TITLE
Lab 5 Ex 2 - Is there a reason to create Warehousexx?

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#47]
Why does the lab have the student create two Azure DW/Synapse dbs?  The compute is expensive (especially relative to Azure Pass), and Warehousexx doesn't seem to be used again.  Why not create DWDB initially in Ex 2 Task 1?

I am undecided whether to tell students not to create Warehousexx or to tell them to immediately pause it after creating.

**Comment by VitalyMCT** [comment]
It's puzzling indeed. The only benefit of this second instance may be to learn how to create Azure Synapse databases via the Azure Portal. 

And yes, there should absolutely be a teardown section at the end to pause both Azure Synapse instances. In Lab 6 for example it's called "Close Down".

**Comment by ctesta-oneillmsft** [comment]
Instruction to Pause it added
