### ISSUE TITLE
Lab 2 - Exercise 3 - Task 1 - Incorrect reference to "first storage account"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#48]
This is the **second** storage account. First one is created earlier in this lab.

![image](https://user-images.githubusercontent.com/1765732/70855770-56e90800-1e9e-11ea-9971-e0f5127ca123.png)

**Comment by ctesta-oneillmsft** [comment]
resolved. Thanks
