### ISSUE TITLE
Lab 2 - Exercise 4 - Task 2 - Behaviour of Azure Storage Explorer has changed

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#49]
Storage Explorer now auto-refreshes by default, so the highlighted sentence should be removed:

![image](https://user-images.githubusercontent.com/1765732/70855987-c6acc200-1ea1-11ea-88dc-5d4eb5ccfeea.png)

Source: https://github.com/microsoft/AzureStorageExplorer/issues/1012#issuecomment-534641598

**Comment by ctesta-oneillmsft** [comment]
Resolved. Thanks
