### ISSUE TITLE
Lab 3 Ex 2 Task 2

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#5]
Due to changes in Azure Databricks task steps should change:

3. In the App registrations screen, click on the +New Registration button
4. Provide the new of DLAccess and URL of https://adventureworks.org/exampleapp for the application. Select Web App for the type of application you want to create.  After seeing the values, select Create.  The DLAccess screen will appear.
5. In the DLAccess registered app screen, copy the Application ID and Tenant ID and paste both into Notepad.
6. In the DLAccess registered app screen, click on Certificates and Secrets, and the click +New Client Secret.
7. Provide a description of DL Access Key, and a duration of In 1 year for the key.  When done, click the Add button.  Copy the key into the Notepad file.

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback, It will be addressed this week

**Comment by ctesta-oneillmsft** [comment]
Adjusted with new instructions:

In the **App registrations** screen, click on the **+ New application registration** button.

1. In the register an application screen, provide the **name** of **DLAccess** and under the **Redirect URI (optional)** section, ensure **Web** is selected and type **https://adventureworks.org/exampleapp** for the application value. After setting the values, select **Register**. The DLAccess screen will appear.

1. In the **DLAccess** registered app screen, copy the **Application ID** and **Tenant ID** and paste both into Notepad.

1. In the **DLAccess** registered app screen, click on **Certificates and Secrets**, and the click **+New Client Secret..**

1. Provide a **description** of **DL Access Key**, and a **duration** of **In 1 year** for the key. When done, click **Save**.

    >**Important**: When you click on Save, the key will appear. You only have one opportunity to copy this key value into Notepad
