### ISSUE TITLE
Lab 3 - Exercise 3 - Task 1 - Terminology

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#53]
The correct term is "**Interactive** Clusters"

![image](https://user-images.githubusercontent.com/1765732/70864140-43c94d00-1f1d-11ea-944f-009d676e5622.png)

**Comment by ctesta-oneillmsft** [comment]
resolved. Thanks
