### ISSUE TITLE
Lab 3 - Exercise 3 - Task 3 - New App Registration Experience

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#54]
The legacy experience has been decommissioned around Nov 14 of this year, so the steps need to be updated:

https://developer.microsoft.com/en-us/identity/blogs/deprecation-of-app-registrations-legacy-experience-and-the-application-registration-portal-apps-dev-microsoft-com/

Examples of changes required:

- "New application registration" button renamed to "New registration"
- The button on "Certificates & secrets" screen renamed from "Save" to "Add"
- The limitation in the following quote no longer applies: 
> Important: When you click on Save, the key will appear. You only have one opportunity to copy this key value into Notepad

**Comment by ctesta-oneillmsft** [comment]
updated. Thanks
