### ISSUE TITLE
Lab 3 - Exercise 3 - Task 4 - Instructions for Scala code out of sync

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#55]
The replacement instructions in Step 7 do not fully match the macros in code block in Step 6. Some macros have different names and some are missing altogether.

![image](https://user-images.githubusercontent.com/1765732/70864836-5abf6d80-1f24-11ea-921e-21c2cfad8af9.png)

**Comment by ctesta-oneillmsft** [comment]
unable to Repro and lab works
