### ISSUE TITLE
Lab 3 - Exercise 4 - Task 3 - Out of place note

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#56]
The following note is from a different lab:      

> Result: After you completed this exercise, you have created a Data Lake Gen II Storage account named awdlsstudxx that has a file system named data that contains two weblog files that are ready to be used by the Data scientists at AdventureWorks.

**Comment by ctesta-oneillmsft** [comment]
Resolved. Thanks
