### ISSUE TITLE
Lab 4 - Scenario - Grammar

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#58]
![image](https://user-images.githubusercontent.com/1765732/70865103-9576d500-1f27-11ea-9b8e-3963b6bc41e2.png)

**Comment by ctesta-oneillmsft** [comment]
Resolved. Thanks

**Comment by rolfr** [comment]
These 2 errors are in many (all?) of the lab exercises, not just the one cited here.

Overall, there are so many typos (some resulting in grammatical nonsense) throughout the Skillpipe book and the exercise docs that it is sometimes difficult to read without pausing to interpret the meanings.
