### ISSUE TITLE
Lab 5 Updates required

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#6]
**Exercise 1 Task 1 Step 4**
1) use Pa55w.rd instead of P@ssw0rd as @ sign may be an issue on some keyboards
2) select the source as Sample and use the AdventureworksLT sample database (used in Lab 7)

**Exercise 2 Task 1 Step 4**
Sample database is not available as a choice now so remove SELECT SOURCE and SELECT SAMPLE parts

**Exercise 4 Task 2 Step 6**
Database credential already exists from step 3, so executing returns error as name already exists.

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback, It will be addressed this week

**Comment by ctesta-oneillmsft** [comment]
P@ssw0rd has been changed to  Pa55w.rd

**Comment by ctesta-oneillmsft** [comment]
Will not be using a sample database in Exercise 1, so this sis unchanged.

**Comment by ctesta-oneillmsft** [comment]
removed the "sample" reference in the instructions as this is no longer a choice in Exercise 2

**Comment by ctesta-oneillmsft** [comment]
Removed the duplicate database scoped credential command

**Comment by ctesta-oneillmsft** [comment]
Mark. Thanks for all of this.
