### ISSUE TITLE
Lab 4 - Exercise 2 - Task 4 - Formatting issue in code block

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#61]
The closing braces are part of the SP code

![image](https://user-images.githubusercontent.com/1765732/70865822-dd99f580-1f2f-11ea-9c9d-0c5a0a67ffcb.png)

**Comment by ctesta-oneillmsft** [comment]
Resolved. Thanks
