### ISSUE TITLE
Lab 4 - Exercise 2 - Task 4 - Incorrect references to SP in UDF section

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#62]
These should all refer to UDF:

![image](https://user-images.githubusercontent.com/1765732/70865904-93654400-1f30-11ea-9959-b883c8b16f7b.png)

**Comment by ctesta-oneillmsft** [comment]
resolved. Thanks
