### ISSUE TITLE
Lab 5 - Exercise 1 - Task 1

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#66]
The name of Azure SQL servers must use lowercase letters. Uppercase letters in server names are not allowed by Azure.

Also, the "allow Azure services to access server" toggle is unavailable in the current server creation dialog.

![image](https://user-images.githubusercontent.com/1765732/70867160-47ba9680-1f40-11ea-93a8-1d297dca317b.png)

**Comment by ctesta-oneillmsft** [comment]
resolved. Thanks
