### ISSUE TITLE
Lab 5 - Exercise 3 - Task 2 - Extra step

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#67]
The following step is unnecessary. There is another storage account that's used later in this lab.

> In the awdlsstudxx blade, click on Access keys, and then clilck on the copy icon next to the Storage account name and paste it into Notepad.

**Comment by ctesta-oneillmsft** [comment]
Lab being updated and released December 20th
