### ISSUE TITLE
Presnetion slide  DP-200T01: Working with Relational Data Stores in the Cloud wrong answers

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#68]
DP-200T01:  Working with Relational Data Stores in the Cloud

answer is wrong 

 Q02 – Mike is the data engineer for Contoso and has a Data Warehouse created with a database name Crystal. He has created a master key, followed by a database scoped credential. What should he create next?
A02 – Strong.
An external data source

**Comment by ctesta-oneillmsft** [comment]
Thanks and  apologies for the delay. This has been updated and will be published next week
