### ISSUE TITLE
Lab 4 - Building Globally Distributed Databases with Cosmos DB

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#71]
The Lab 4 is reference the locations for lab file "Lab files: The files for this lab are located in the Allfiles\Labfiles\Starter\DP-200.4 folder."

But there are no lab files at /Labfiles/Starter/DP-200.4/ . Only include this information "There are no labfiles in this folder".

**Comment by ctesta-oneillmsft** [comment]
There is a Readme file that states there are no labfiles for this lb
