### ISSUE TITLE
Lab 5 needs to be reviewed.

### ISSUE THREAD

**Issue by 1VivekKumar** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#73]
Lab 5 needs to be reviewed. Data folder and DimDate2.txt need to be uploaded to storage account. DWHserver need to be used at some place where there is typing error.

**Comment by ctesta-oneillmsft** [comment]
Thanks @1VivekKumar. Looks like only half the instructions got published. I am looking into this now

**Comment by ctesta-oneillmsft** [comment]
lab updates published and tested. the lab now runs
