### ISSUE TITLE
CosmosDB SP error in execution

### ISSUE THREAD

**Issue by RuggieroLauria** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#75]
After the SP creation:

function createMyDocument() {
    var context = getContext();
    var collection = context.getCollection();

    var doc = {
        "id": "3",
        "productid": "33218898",
        "description": "Contoso microfleece zip-up jacket",
        "price": "44.99"
    };
   
    var accepted = collection.createDocument(collection.getSelfLink(),
        doc,
        function (err, documentCreated) {
            if (err) throw new Error('Error' + err.message);
            context.getResponse().setBody(documentCreated)
        });
    if (!accepted) return;
}

When I run it supplying the Partition Key value (as string): 33218896
I get the error:
Failed to execute stored procedure createMyDocument for container Clothing: {"code":400,"body":{"code":"BadRequest","message":"Message: {\"Errors\":[\"Encountered exception while executing function. Exception = Error: Error{\\\"Errors\\\":[\\\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\\\"]}\\r\\nStack trace: Error: Error{\\\"Errors\\\":[\\\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\\\"]}\\n   at Anonymous function (script.js:16:22)\\n   at Anonymous function (script.js:685:29)\"]}\r\nActivityId: 72451198-6cbe-4e4a-85b4-2c01b64f313e, Request URI: /apps/17d358cf-f9b4-47d9-800d-f8a7286d322e/services/abeb40bd-9b61-4a56-9f4a-a0b15f902c6c/partitions/173fcce2-8f8a-4eb1-b67e-c1b98e00b499/replicas/132225621016604590p, RequestStats: \r\nRequestStartTime: 2020-01-05T13:36:30.3649191Z, RequestEndTime: 2020-01-05T13:36:30.3649191Z,  Number of regions attempted:1\r\nResponseTime: 2020-01-05T13:36:30.3649191Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.102:14000/apps/17d358cf-f9b4-47d9-800d-f8a7286d322e/services/abeb40bd-9b61-4a56-9f4a-a0b15f902c6c/partitions/173fcce2-8f8a-4eb1-b67e-c1b98e00b499/replicas/132225621016604590p, LSN: 10, GlobalCommittedLsn: 10, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 2.99, ItemLSN: -1, SessionToken: -1#10, UsingLocalLSN: False, TransportException: null, ResourceType: StoredProcedure, OperationType: ExecuteJavaScript\r\n, SDK: Microsoft.Azure.Documents.Common/2.7.0"},"headers":{"access-control-allow-credentials":"true","access-control-allow-origin":"https://cosmos.azure.com","content-type":"application/json","lsn":"10","strict-transport-security":"max-age=31536000","x-ms-activity-id":"72451198-6cbe-4e4a-85b4-2c01b64f313e","x-ms-cosmos-llsn":"10","x-ms-cosmos-quorum-acked-llsn":"10","x-ms-current-replica-set-size":"4","x-ms-current-write-quorum":"3","x-ms-gatewayversion":"version=2.7.0","x-ms-global-committed-lsn":"10","x-ms-last-state-change-utc":"Fri, 03 Jan 2020 21:55:08.123 GMT","x-ms-number-of-read-regions":"0","x-ms-quorum-acked-lsn":"10","x-ms-request-charge":"2.99","x-ms-schemaversion":"1.9","x-ms-serviceversion":"version=2.7.0.0","x-ms-session-token":"0:-1#10","x-ms-transport-request-id":"4","x-ms-xp-role":"1","x-ms-throttle-retry-count":0,"x-ms-throttle-retry-wait-time-ms":0},"activityId":"72451198-6cbe-4e4a-85b4-2c01b64f313e"}

**Comment by RuggieroLauria** [comment]
Found a solution: you have to pass the value 33218896 as Partiton Key and also as input parameters (both as string)

**Comment by davidcwalls** [comment]
@RuggieroLauria Did you also change the productId in the body of the SP (since the instructions call for using 33218898)?  I'm getting this error now (though I have resolved it before, I can't remember how), and have tried various combinations without success.

**Comment by Derekp20** [comment]
Have you got the correct case for the characters. It should be ProductId,  not productid. It is case sensitive in definition of the partion key and in the stored procedure.

Derek

**Comment by davidcwalls** [comment]
Thanks!  It wasn't the "P", but I checked my partition key and it had a lowercase "i" (typo on my part)

I'm curious why you use a capital "P" - Each of the 16 times "productId" is used in the instructions for lab 4, the only capital letter is "I",  i.e. in the Add Container command, in the JSON for inserting the first two items, and in the stored procedure code.

**Comment by begler1** [comment]
We get the same error and tried all the suggestions above but no luck. Any resolution?

**Comment by davidcwalls** [comment]
@begler1 The things I found that would cause the "cannot reference partition keys" error are:

- if the property name in your code (e.g. productId) is not exactly the same as the partition key in the settings of the container (or if the partition key property is missing in the code), and 
- if the type of the partition key in the Input Parameters dialog is not changed from Custom to String  when you execute it

**Comment by begler1** [comment]
Thanks for the clarification. That works!

**Comment by AndresLAraque** [comment]
La intuición de @Derekp20 es correcta, El error pertenece al que productId debe estar en mayusculas, 
Adjunto el codigo, espero sea de ayuda, Saludos


function createMyDocument() { 
    var context = getContext(); 
    var collection = context.getCollection();

    var doc = { 
        "id": "3", 
        "ProductId": "33218898", 
        "description": "Contoso microfleece zip-up jacket", 
        "price": "44.99" 
        }; 
        
        var accepted = collection.createDocument(collection.getSelfLink(), 
        doc, 
        function (err, documentCreated) { 
            if (err) throw new Error('Error' + err.message); 
            context.getResponse().setBody(documentCreated) 
            }); 
            if (!accepted) return; 
    }

**Comment by Petartechiguru** [comment]
Hvala al ne govorim Španski.
Sorry jo ne ablo espanjol
