### ISSUE TITLE
Lab 5, Ex. 4: Sample query isn't generalized

### ISSUE THREAD

**Issue by rolfr** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#76]
Lab 5, Exercise 4: Using PolyBase to Load Data into Azure Synapse Analytics

The step to create the external database has someone’s personal storage account name “'abfs://data@awdlsstudcto.dfs.core.windows.net'. I blindly copy/pasted this query and had problems later, so had to start my DW all over again. The sample should use ‘awdlsstudxx’  to indicate that this should be replaced with my own account name, and perhaps additionally mention in the instructions that it should be replaced (mainly because that's the pattern throughout most of the docs.)

**Comment by ctesta-oneillmsft** [comment]
Thanks. This has been updated and will be deployed soon
