### ISSUE TITLE
Lab 6, Ex. 2: Screenshot doesn't match instructions

### ISSUE THREAD

**Issue by rolfr** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#77]
Lab 6, Exercise 2: Data Ingestion with Event Hubs

Task 1 says to enable auto-inflate with throughput units of 20 (and implies to leave initial throughput units at 1.)  It is followed by a screenshot that has auto-inflate disabled and initial throughput units of 20.

**Comment by ctesta-oneillmsft** [comment]
Thanks. The instruction has been cleaned up to reflect the image and will be deployed soon
