### ISSUE TITLE
az configure --defaults group=<rgn>[sandbox resource group name]</rgn> sql-server=<server-name>

### ISSUE THREAD

**Issue by RuggieroLauria** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#78]
Gives an error regarding the API:

The api-version '2017-10-01-preview' is invalid. The supported versions are '2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

**Comment by ctesta-oneillmsft** [comment]
Hello @RuggieroLauria 

PLeasr can you outline which lab, exercise and task? Where is this happening? and are you using the course VM?

**Comment by RuggieroLauria** [comment]
Module 5: What is Azure Cloud Shell?
Get information about your Azure SQL database

az sql db list

when you launch the command above you receive the error described

This happens in the Azure portal.

**Comment by ctesta-oneillmsft** [comment]
Are you sure you have the right course? We don't even use the cloud shell in Lab 5, Closing this as it is not related to this course

**Comment by RuggieroLauria** [comment]
Trainer handbook pag 199 Chris

**Comment by ctesta-oneillmsft** [comment]
That explains why I cant see it. Let me repro the handbook

**Comment by ctesta-oneillmsft** [comment]
Hi. I just setup a database and ran the commands and verified it worked. It must have been a transient issue you were experience Ruggiero, Thanks for raising this

**Comment by jpabloh** [comment]
Hi Chris,

I'm too having the same issue, I don't think this is a transient issue. I'm followin the Trainer Handbook page 209 (Get information about your Azure SQL database). Here are the commands that I run:

az configure --defaults group=<rgn>dp200jph</rgn> sql-server=jphdp200server

Result: Nothing, but no errors.

az sql db list

Result: BadRequestError: The api-version '2019-06-01-preview' is invalid. The supported versions are '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

I already did an upgrade (az upgrade) T
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.18.0

In my case I'm using the Powershell version of Azure Cli in the Azure Portal :

az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "azure-cli-ml": "1.20.0"
  }
}

Thanks!
