### ISSUE TITLE
Lab 2 Ex 2 Task 2 Step 3 - Need to Type more than "Storage"

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#81]
The step asks the student to type "storage" and choose Storage Account from the list.  However, Storage Account does not appear in the context-sensitive list unless I continue to type "storage A".  (If I search for "storage", i.e. type storage and press Enter, Storage Account does show in the results, but it seems like it might be confusing to students as it is.)

I suggest directing the student to type "storage account" instead of "storage"

**Comment by ctesta-oneillmsft** [comment]
changed
