### ISSUE TITLE
Lab 2 Ex 3 Task 2: File System -> Container

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#82]
Steps 3 and 5, text and graphic need to be updated to reflect that "File System" has been replaced with "Container" in the UI.

**Comment by ctesta-oneillmsft** [comment]
It seems to change on a daily basis....  but has been updates and will be deployed later today

**Comment by Datachick** [comment]
Looks like it is back to Container now?

**Comment by ctesta-oneillmsft** [comment]
Thanks for the feedback Karen, we will get this added to the backlog
