### ISSUE TITLE
dp-200-05_instructions.md - Lab 5 Ex 2 Task 2 Step 1 Correction needed

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#84]
"In the Azure portal, in the blade, click Resource groups, and then click awrgstudxx, and then click on awdlsstudxx, where xx are your initials"

should be:

"In the Azure portal, in the blade, click Resource groups, and then click awrgstudxx, where xx are your initials"

**Comment by ctesta-oneillmsft** [comment]
It is asking you to click on your resource group, and then click on the data lake store, of which both finish with your initials
