### ISSUE TITLE
Azure Pass Account does not allow the creation of the cluster in Lab3

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#85]
I am running the course in Australia and I tried different regions to see if I could find one that would allow the cluster to be created. I couldn't find one. As students will be using the Azure Pass Account I don't know how to make the lab work. Maybe there is some region that works. Any clues? I already tried East US and West US after of course trying the Australian ones.

**Comment by ikdonev** [comment]
So far there is a Azure-wide restriction imposed over Azure Pass subscriptions - [link](https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/) I am facing the same issue, particularly around services/labs, requiring VM provisioning.

**Comment by ctesta-oneillmsft** [comment]
please see this article

https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&Id=375289
