### ISSUE TITLE
Lab 8 - Actual auditing results differ from expected results

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#86]
Running through this lab again here and for some reason the "DATABASE AUTHENTICATION FAILED" messages are missing from the log in Exercise 4. Tried with both SSMS and Azure Data Studio as client tools.

Auditing is enabled in Azure at both database and server levels. All success messages are coming through exactly as expected.

I am pretty sure this worked fine before. It kind of looks like an Azure SQL Database product bug. I cannot see anything I may be doing wrong. Though that would be a pretty big bug, so my first suspicion is always user error :)

Has anyone seen the same issue? If so, what was the workaround?

**Comment by ctesta-oneillmsft** [comment]
I tried to repo the issue on an Enterprise login and could not get the issue.

At this time there are restrictions on Azure, please read the following article.

https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&Id=375289

Once the restrictions are lifted, the issue should not be there

**Comment by VitalyMCT** [comment]
This is happening for all subscriptions here, including normal corporate Pay-As-You-Go subscriptions. Can you send a link that says partial auditing failures within existing Azure SQL Database instances are related to Azure capacity restrictions? I can't see any possible connection at all.
