### ISSUE TITLE
Lab 4 Exercise 4 Task 3 - error due to existing users

### ISSUE THREAD

**Issue by tomazzg** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#87]
It seems that I have some problem with the code execution. After inserting the two users I get this error message:
*Database and collection validation complete
Error: One or more errors occurred. (Entity with the specified id already exists in the system., 
RequestStartTime: 2020-04-17T18:19:34.5615751Z, RequestEndTime: 2020-04-17T18:19:34.5615751Z,  Number of regions attempted:1
ResponseTime: 2020-04-17T18:19:34.5615751Z, StoreResult: StorePhysicalAddress: rntbd://bluprdapp02-docdb-1.documents.azure.com:14469/apps/cf7ce45a-ad86-401b-88b9-51807b88ba7a/services/a58186d9-f548-4879-89f3-e0096b61a7d4/partitions/933cb6db-76a4-4639-b753-1348c27b24cc/replicas/132303429420297514p/, LSN: 3, GlobalCommittedLsn: 3, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create
, Microsoft.Azure.Documents.Common/2.10.0
ActivityId: 2728cdbc-81da-455a-8d19-1fec6366cf52, Windows/10.0.18363 documentdb-netcore-sdk/2.10.1), Message: Entity with the specified id already exists in the system., 
RequestStartTime: 2020-04-17T18:19:34.5615751Z, RequestEndTime: 2020-04-17T18:19:34.5615751Z,  Number of regions attempted:1
ResponseTime: 2020-04-17T18:19:34.5615751Z, StoreResult: StorePhysicalAddress: rntbd://bluprdapp02-docdb-1.documents.azure.com:14469/apps/cf7ce45a-ad86-401b-88b9-51807b88ba7a/services/a58186d9-f548-4879-89f3-e0096b61a7d4/partitions/933cb6db-76a4-4639-b753-1348c27b24cc/replicas/132303429420297514p/, LSN: 3, GlobalCommittedLsn: 3, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create
, Microsoft.Azure.Documents.Common/2.10.0
ActivityId: 2728cdbc-81da-455a-8d19-1fec6366cf52, Windows/10.0.18363 documentdb-netcore-sdk/2.10.1
End of demo, press any key to exit.*
I believe that the Task **CreateUserDocumentIfNotExists** doesn't catch the user id and goes on to create new items.
I also attached the programm.cs
[Program.zip](https://github.com/MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution/files/4494627/Program.zip)

**Comment by Derekp20** [comment]
Line 130 you have user_id instead of userId See the instructions for Task 3 Step 2

**Comment by tomazzg** [comment]
Thanks Derek.

Sorry, I forgot to mention. This was willingly put there, user_Id is the name of my partition key in the collection

**Comment by tomazzg** [comment]
I deleted the key and made a new collection. Now it works! THX
