### ISSUE TITLE
Module 3 Data Bricks Lab

### ISSUE THREAD

**Issue by Petartechiguru** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#88]
Exercise 2 gives an error when trying to create a new cluster in the data brick service

Cloud Provider Launch Failure: 
A cloud provider error was encountered while setting up the cluster. See the Databricks guide for more information.

Azure error code: OperationNotAllowed

Azure error message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 4, Current Usage: 4, Additional Required: 4, (Minimum) New Limit Required: 8. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22ebf4a692-4ad2-4eb1-aa1b-1d8311fafc3a%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.

**Comment by Petartechiguru** [comment]
Most students are on pay as you go and azure passes.
What can be please done for them to move forward on the lab?
With trial accounts of $200 credit a quota request is not possible since is a pay as you go and requires to convert to upgraded account.

**Comment by Petartechiguru** [comment]
Hello any help on this issue please?

**Comment by Petartechiguru** [comment]
We found this is not an issue if using the azure pass.

**Comment by parveenkrraina** [comment]
You can try creating the cluster using these settings:

- Disable autoscaling
- Min Workers 1
