### ISSUE TITLE
Module 4 Exercise 2 Task4

### ISSUE THREAD

**Issue by Petartechiguru** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#89]
Need correct stored procedure please ->
For stored procedure code:
function createMyDocument() {
    var context = getContext();
    var collection = context.getCollection();

    var doc = {
        "id": "3",
        "productId": "33218898",
        "description": "Contoso microfleece zip-up jacket",
        "price": "44.99"
    };

    var accepted = collection.createDocument(collection.getSelfLink(),
        doc,
        function (err, documentCreated) {
            if (err) throw new Error('Error' + err.message);
            context.getResponse().setBody(documentCreated)
        });
    if (!accepted) return;
}

With executing with:
In the Input Parameters screen, type should be set to string, and value set to 33218898 in the Partition Key Value text box, and then click Execute.

Get error:
Failed to execute stored procedure createMyDocument for container Clothing: {"code":400,"body":{"code":"BadRequest","message":"Message: {\"Errors\":[\"Encountered exception while executing function. Exception = Error: Error{\\\"Errors\\\":[\\\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\\\"]}\\r\\nStack trace: Error: Error{\\\"Errors\\\":[\\\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\\\"]}\\n   at Anonymous function (script.js:15:22)\\n   at Anonymous function (script.js:686:29)\"]}\r\nActivityId: d1129a15-2619-404b-b9fd-f5dfa85671c8, Request URI: /apps/daf902b6-87b6-4838-98cf-4d76449b3c6d/services/7474d23f-7ca9-483c-a049-4a7b372954c7/partitions/68059e10-3e34-432f-9848-cf2b82c3017f/replicas/132340635048243079p/, RequestStats: \r\nRequestStartTime: 2020-05-18T05:28:11.8771520Z, RequestEndTime: 2020-05-18T05:28:11.9371321Z,  Number of regions attempted:1\r\nResponseTime: 2020-05-18T05:28:11.9371321Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd2.documents.azure.com:14471/apps/daf902b6-87b6-4838-98cf-4d76449b3c6d/services/7474d23f-7ca9-483c-a049-4a7b372954c7/partitions/68059e10-3e34-432f-9848-cf2b82c3017f/replicas/132340635048243079p/, LSN: 17, GlobalCommittedLsn: 17, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 3.44, ItemLSN: -1, SessionToken: 2#17#8=-1, UsingLocalLSN: False, TransportException: null, ResourceType: StoredProcedure, OperationType: ExecuteJavaScript\r\n, SDK: Microsoft.Azure.Documents.Common/2.11.0"},"headers":{"access-control-allow-credentials":"true","access-control-allow-origin":"https://cosmos.azure.com","content-type":"application/json","lsn":"17","strict-transport-security":"max-age=31536000","x-ms-activity-id":"d1129a15-2619-404b-b9fd-f5dfa85671c8","x-ms-cosmos-llsn":"17","x-ms-cosmos-quorum-acked-llsn":"17","x-ms-current-replica-set-size":"4","x-ms-current-write-quorum":"3","x-ms-gatewayversion":"version=2.11.0","x-ms-global-committed-lsn":"17","x-ms-last-state-change-utc":"Sat, 16 May 2020 00:45:21.473 GMT","x-ms-number-of-read-regions":"1","x-ms-quorum-acked-lsn":"17","x-ms-request-charge":"3.44","x-ms-schemaversion":"1.9","x-ms-serviceversion":"version=2.11.0.0","x-ms-session-token":"0:2#17#8=-1","x-ms-transport-request-id":"1","x-ms-xp-role":"1","x-ms-throttle-retry-count":0,"x-ms-throttle-retry-wait-time-ms":0},"activityId":"d1129a15-2619-404b-b9fd-f5dfa85671c8"}

**Comment by ctesta-oneillmsft** [comment]
retested this code, and I can't repo the error you have.The following result is returned.

{
    "id": "3",
    "productId": "33218898",
    "description": "Contoso microfleece zip-up jacket",
    "price": "44.99",
    "_rid": "I2YsALxG+-EDAAAAAAAAAA==",
    "_self": "dbs/I2YsAA==/colls/I2YsALxG+-E=/docs/I2YsALxG+-EDAAAAAAAAAA==/",
    "_etag": "\"0000874e-0000-1a00-0000-5ca7a7050000\"",
    "_attachments": "attachments/"
}
```

Closing
