### ISSUE TITLE
Module 2, Exercise 4, Task 1, Step 3

### ISSUE THREAD

**Issue by dancostello70** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#91]
...seems not to be valid any more -- no evidence of a download link for Storage Explorer.

**Comment by Derekp20** [comment]
Maybe change to: Click on _Overview_, then click _Open in Explorer_ the link is then shown.

**Comment by ctesta-oneillmsft** [comment]
Thank you both. Updated
