### ISSUE TITLE
instructions/dp-200-02_instructions.md: Ex 3 Task 2:

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#93]
instructions/dp-200-02_instructions.md: Ex 3 Task 2:
--
Step 4: "From the New screen, create two file systems with the following name:" should be "From the New screen, create two containers with the following names:"
 Step 5: "click **OK**." should be "click **Create** each time."

**Comment by ctesta-oneillmsft** [comment]
Thank you
