### ISSUE TITLE
instructions/dp-200-03_instructions.md: Ex 2 Task 3 Step 3: Spark version unavailable

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#96]
instructions/dp-200-03_instructions.md: Ex 2 Task 3 Step 3: Spark version unavailable
--
"Databricks Runtime Version: Runtime: 6.2 (Scala 2.11, Spark 2.4.4)"

should be:

"Databricks Runtime Version: Runtime: 6.3 (Scala 2.11, Spark 2.4.4)"

**Comment by ctesta-oneillmsft** [comment]
Thank you. updated
