### ISSUE TITLE
instructions/dp-200-04_instructions.md: Ex 4 Task 4 Step 3: New extension name

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#97]
instructions/dp-200-04_instructions.md: Ex 4 Task 4 Step 3: New extension name
--
"Azure Cosmos DB" extension is now called "Azure Databases for VS Code (Preview)"

UI has also changed so instructions need to be updated throughout.

**Comment by ctesta-oneillmsft** [comment]
Thanks Begler1. The decision has been made to remove this optional lab as feedback is stating that it is too developer focused
