### ISSUE TITLE
Rewording required at Lab 5 Excercise 2, Task 2

### ISSUE THREAD

**Issue by meetnavpk** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#98]
In the Azure portal, in the blade, click Resource groups, and then click awrgstudxx, and then click on awdlsstudxx, where xx are your initials

to 

In the Azure portal, in the blade, click Resource groups, and then click awrgstudxx, where xx are your initials

**Comment by ctesta-oneillmsft** [comment]
resolved and released
